name: Production Release

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force publish all packages?
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Run if force
        if: ${{ inputs.force }}
        run:  echo "Forcce!"

      - name: Run if not focr
        if: ${{ !inputs.force }}
        run:  echo "Not Forcce!"